GPMGMT_SRC=$(CURDIR)
BEHAVE_BIN=$(GPMGMT_SRC)/bin/pythonSrc/ext/install/bin/behave
TAR?=$(shell which tar)
PEXPECT_LIB=$(GPHOME)/bin/lib

# If install_behave is used, make sure to append $BEHAVE_BIN to
# $PYTHONPATH before running the behave tests.
install_behave:
	TAR=$(TAR) make -C bin $(BEHAVE_BIN)

# To pass in custom flags as behave args(such as multiple flags),
# use flags=--tags=foo, --tags=-bar
behave:
	@echo "Running behave on management scripts..."
	@if [ -n """$(flags)""" ]; then \
		PYTHONPATH=$(GPMGMT_SRC):$(PEXPECT_LIB):$(PYTHONPATH) behave $(GPMGMT_SRC)/test/behave/* -s -k $(flags) 2>&1 ; \
	elif [ -n """$(tags)""" ]; then \
		PYTHONPATH=$(GPMGMT_SRC):$(PEXPECT_LIB):$(PYTHONPATH) behave $(GPMGMT_SRC)/test/behave/* -s -k --tags=$(tags) 2>&1 ; \
	else \
		echo "Please specify tags=tagname or flags=[behave flags]"; \
		exit 1; \
	fi
